name: brigada
description: Brigada Application

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.4+8
  image_picker: ^0.6.2
  path_provider: ^1.2.0
  image: ^2.0.7
  uuid: ^2.0.2
  cached_network_image: ^1.1.3
  modal_progress_hud: ^0.1.3
  geolocator: ^5.2.0
  google_maps_flutter: ^0.5.13
  timeago: ^2.0.22
  intl: ^0.16.1
  simple_animations: ^1.3.3
  url_launcher: ^5.2.0
  flutter_email_sender: ^2.2.2
  flutter_sms: ^1.1.0
  simple_sms: ^0.0.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter

 
  firebase_auth: ^0.15.0
  cloud_firestore: ^0.12.10
  firebase_storage: ^3.0.0


flutter:

 
  uses-material-design: true

  assets:
   - assets/images/



  fonts:
    - family: Montserrat-Regular
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf

    - family: Montserrat-Light
      fonts:
        - asset: assets/fonts/Montserrat-Light.ttf

    - family: Montserrat-Bold
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf

    - family: FredokaOne
      fonts:
        - asset: assets/fonts/FredokaOne-Regular.ttf
